services:
        --- Monitoramento ---
        uptime-kuma:
          image: louislam/uptime-kuma:1
          container_name: uptime-kuma
          restart: unless-stopped
          volumes:
            - ./uptime-kuma/data:/app/data
