version: "3.3"
      services:
        --- Homepage ---
        homepage:
          image: gethomepage/homepage:latest
          container_name: homepage
          environment:
            - HOMEPAGE_ALLOWED_HOSTS=seu_ip_com_porta
          restart: unless-stopped
          volumes:
            - ./config:/app/config
            - /var/run/docker.sock:/var/run/docker.sock:ro
          ports:
            - "8082:3000"
